export const DATA_ROM = [
  { value: '8', label: '8GB' },
  { value: '16', label: '16GB' },
  { value: '32', label: '32GB' },
  { value: '64', label: '64GB' },
  { value: '128', label: '128GB' },
  { value: '256', label: '256GB' },
  { value: '512', label: '512GB' },
  { value: '1', label: '1TB' },
  { value: '2', label: '2TB' },
];

export const DATA_SCREEN = [
  { value: 'amoled', label: 'AMOLED' },
  { value: 'ips-quantum', label: 'IPS Quantum (IPS lượng tử)' },
  { value: 'led-backlit-ips-lcd', label: 'LED-backlit IPS LCD' },
  { value: 'clearblack', label: 'ClearBlack' },
  { value: 'ips-lcd', label: 'IPS LCD' },
  { value: 'super-lcd', label: 'Super LCD (S-LCD)' },
  { value: 'tft-lcd', label: 'Màn hình TFT-LCD' },
  { value: 'lcd', label: 'Màn hình LCD' },
  { value: 'ltps-lcd', label: 'LTPS LCD' },
  { value: 'tn', label: 'TN' },
  { value: 'pls-lcd', label: 'PLS LCD' },
  { value: 'pls-lcd', label: 'Màn hình Super Retina XDR' },
];

export const DATA_RAM = [
  { value: '1', label: '1GB' },
  { value: '2', label: '2GB' },
  { value: '3', label: '3GB' },
  { value: '4', label: '4GB' },
  { value: '6', label: '6GB' },
  { value: '8', label: '8GB' },
  { value: '12', label: '12GB' },
  { value: '16', label: '16GB' },
  { value: '18', label: '18GB' },
  { value: '32', label: '32GB' },
  { value: '64', label: '64GB' },
];

export const DATA_BRAND_LT = [
  { value: "gigabyte", label: "Gigabyte" },
  { value: "asus", label: "Asus" },
  { value: "huawei", label: "Huawei" },
  { value: "apple", label: "Apple" },
  { value: "xiaomi", label: "Xiaomi" },
  { value: "hp", label: "HP" },
  { value: "msi", label: "MSI" },
  { value: "acer", label: "Acer" },
  { value: "lenovo", label: "Lenovo" },
  { value: "dell", label: "Dell" },
  { value: "lg", label: "LG" },
  { value: "microsoft", label: "Microsoft" },
  { value: "itel", label: "Itel" },
];

export const DATA_CHIP_LAPTOP =
  [
    { value: "core-i5", label: "Core i5" },
    { value: "core-i7", label: "Core i7" },
    { value: "core-i3", label: "Core i3" },
    { value: "ryzen-5", label: "Ryzen 5" },
    { value: "ryzen-7", label: "Ryzen 7" },
    { value: "apple-m2", label: "Apple M2" },
    { value: "m3", label: "M3" },
    { value: "apple-m1", label: "Apple M1" },
    { value: "celeron", label: "Celeron" },
    { value: "m3-pro", label: "M3 Pro" },
    { value: "apple-m1-8-core", label: "Apple M1 8-core" },
    { value: "m2", label: "M2" },
    { value: "core-i9", label: "Core i9" },
    { value: "ryzen-3", label: "Ryzen 3" },
  ];

  export const DATA_CHIP = [
    'Qualcomm Snapdragon 8 Gen 3',
    'Dimensity 9200 Plus97',
    'Snapdragon 8 Gen 2',
    'MediaTek Dimensity 9200',
    'Qualcomm Snapdragon 8 Plus Gen 1',
    'Google Tensor G3',
    'MediaTek Dimensity 9000 Plus',
    'Snapdragon 7 Plus Gen 2',
    'Qualcomm Snapdragon 8 Gen 1',
    'MediaTek Dimensity 9000',
    'Samsung Exynos 2200',
    'Google Tensor',
    'Qualcomm Snapdragon 888 Plus',
    'Kirin 9000',
    'Qualcomm Snapdragon ',
    'Dimensity 8200',
    'Samsung Exynos 2100',
    'Google Tensor G2',
    'MediaTek Dimensity 8100',
    'MediaTek Dimensity 1300',
    'MediaTek Dimensity 1100',
    'Qualcomm Snapdragon 865 Plus',
    'MediaTek Dimensity 7200 Ultra',
    'Dimensity 8020',
    'MediaTek',
    'MediaTek Dimensity 1200',
    'Qualcomm Snapdragon 870',
    'Dimensity 8050',
    'MediaTek',
    'HiSilicon Kirin 9000S',
    'Dimensity 7200',
    'Qualcomm Snapdragon 865',
    'HiSilicon Kirin 990 (4G)',
    'Exynos 990',
    'Qualcomm Snapdragon 7 Gen 1',
    'HiSilicon Kirin 990 (5G)',
    'Qualcomm Snapdragon 782G',
    'MediaTek Dimensity 1000 Plus',
    'Qualcomm Snapdragon 7s Gen 2',
    'Exynos 1380',
    'Samsung Exynos 9820',
    'Qualcomm Snapdragon 778G Plus',
    'Qualcomm Snapdragon 780G',
    'Exynos 9825',
    'Qualcomm Snapdragon 855',
    'MediaTek Dimensity 9300',
  ];

  export const DATA_CHIP_APPLE = [
    { value: "apple-a17-pro", label: "Apple A17 Pro" },
    { value: "apple-a16-bionic", label: "Apple A16 Bionic" },
    { value: "apple-a15-bionic", label: "Apple A15 Bionic" },
    { value: "apple-a14-bionic", label: "Apple A14 Bionic" },
    { value: "apple-a13-bionic", label: "Apple A13 Bionic" },
    { value: "apple-a12-bionic", label: "Apple A12 Bionic" },
  ];

  export const DATA_BRAND_DT = [
    { value: 'apple', label: 'Apple' },
    { value: 'msi', label: 'MSI' },
    { value: 'samsung', label: 'Samsung' },
    { value: 'xiaomi', label: 'Xiaomi' },
    { value: 'oppo', label: 'OPPO' },
    { value: 'tecno', label: 'TECNO' },
    { value: 'nokia', label: 'Nokia' },
    { value: 'realme', label: 'realme' },
    { value: 'vivo', label: 'Vivo' },
    { value: 'honor', label: 'HONOR' },
    { value: 'htc', label: 'HTC' },
    { value: 'infinix', label: 'Infinix' },
    { value: 'rog', label: 'ROG' },
    { value: 'nubia', label: 'Nubia' },
    { value: 'xor', label: 'XOR' },
    { value: 'masstel', label: 'Masstel' },
    { value: 'tcl', label: 'TCL' },
    { value: 'itel', label: 'Itel' },
    { value: 'lg', label: 'LG' },
    { value: 'huawei', label: 'Huawei' },
  ];